Подключает шрифты, добавляет базовую стилизацию
htmlacademy-htmlcss/2366847-device-1 pull request #1
Opened 2023-08-07 08:36 UTC by KseniaT3

Добавляет базовую стилизацию текста,  подключает шрифты

2023-08-07 21:28 UTC, Ankhena requested changes

2023-08-07 21:28 UTC, Ankhena commented on index.html
> +    <title>Интернет-магазин гаджетов device</title>
Названия и имена собственные лучше писать в большой буквы

2023-08-07 21:28 UTC, Ankhena commented on index.html
> +          <img src="images/header/search.svg" width="16" height="16" alt="Поиск">
Лупа это украшение поля поиска, лучше делать через стили. 
А img - это важные контентные изображения

2023-08-07 21:28 UTC, Ankhena commented on index.html
> +        <form action="https://echo.htmlacademy.ru" method="POST">
Я бы не стала включать форму в навигацию, если есть такая возможность.

2023-08-07 21:28 UTC, Ankhena commented on index.html
> +        <form action="https://echo.htmlacademy.ru" method="POST">
action и method - отлично

2023-08-07 21:28 UTC, Ankhena commented on index.html
> +            <a class="navigation-link" href="#">
Очень интересный получился текст.
"Два товара. Корзина."
Будет лучше, если он будет человеко-понятным.

2023-08-07 21:28 UTC, Ankhena commented on index.html
> +              <li><a class="main-navigation-link-list transform-none" href="#">Моноподы для селфи</a></li>
Будет супер, если в меню будет ссылка на вторую страницу. 
По логике она должна быть с моноподов для селфи. 
Но пока не сделана выпадашка меню, можно и со слов Каталог товаров. 
Так и тебе и мне будет удобнее перемещаться между страницами.

2023-08-07 21:28 UTC, Ankhena commented on index.html
> +      <a class="page-header-logo" href="index.html">
Если на главной мы не убираем ссылку с логотипа, то хорошо бы дописать `aria-current="page"`

2023-08-07 21:28 UTC, Ankhena commented on index.html
> +        <a class="contacts-phone" href="tel:+7(812)812-12-12"></a>
```suggestion
        <a class="contacts-phone" href="tel:+78128121212">+7(812)812-12-12</a>
```

2023-08-07 21:28 UTC, Ankhena commented on index.html
> +        <li class="footer-social-item">
Кажется, один лишний

2023-08-07 21:28 UTC, Ankhena commented on index.html
> +      <a class="htmlacademy-link" href="#">
Не забудь посмотреть куда должна вести эта ссылка

2023-08-07 21:28 UTC, Ankhena commented on index.html
> +        <input type="submit" class="button" value="Отправить">
Кнопки удобнее делать тегом button.
вариант и с инпутом можно использовать, но:

- он устаревший, так делали, когда не было тега button
- у инпута текст, который будет написан на кнопке, нужно указывать в value (это дичь с точки зрения логики)
- инпут - одиночный тег, у него нет псевдоэлементов и внутрь нельзя вставить какие-то теги типа span, а значит могут быть проблемы при стилизации и добавлении текста для читалок или его скрытия.

2023-08-07 21:28 UTC, Ankhena commented on catalog.html
> +            <a class="catalog-breadcrumb-link" href="catalog.html">Моноподы для селфи</a>
Либо не нужна ссылка
Либо её не нужен href
Либо ей нужно добавить `aria-current="page"`

2023-08-07 21:28 UTC, Ankhena commented on catalog.html
> +        </div>-->
```suggestion
<fieldset>
        <legend>Стоимость</legend>
        <!-- <div class="slidecontainer">
          <input type="range" min="1" max="#" value="50" class="slider" id="myRange">
        </div>-->
</fieldset>        
```

2023-08-07 21:28 UTC, Ankhena commented on catalog.html
> +        </ul>
Вперед и назад не являются элементами списка страниц.

2023-08-07 21:28 UTC, Ankhena commented on styles/styles.css
> +  font-family: Raleway;
Семейство шрифтов потерялось. 
Обязательно, во всех местах должно быть указано семейство.

Если умеешь использовать кастомные свойства, то тут может пригодиться и заметно облегчить работу и возможную смену шрифта.

2023-08-07 21:28 UTC, Ankhena commented on styles/styles.css
> +}
Глобальные селекторы запрещены. 
В идеале заменить на классы. 
Если очень не хочется, то селектором по родителю, задав класс самой таблице или блоку.

2023-08-07 21:28 UTC, Ankhena commented on styles/styles.css
> +.product-card .product-card-title {
А зачем тут вложенный селектор?

2023-08-07 21:28 UTC, Ankhena commented on styles/styles.css
> +.about-title .about-description {
Зачем тут вложенность селектора?

2023-08-07 21:28 UTC, Ankhena commented on styles/styles.css
> +}
Не хочешь для одинаковых заголовков задать один класс и не повторять стили?

2023-08-08 13:50 UTC, KseniaT3 commented on styles/styles.css
> +}
я сделала класс title-level-two
заменила везде где одно и то же. Отключились стили от этих элементов и потянулись из body.

2023-08-08 13:55 UTC, KseniaT3 commented on styles/styles.css
> +.about-title .about-description {
Здесь удалила вообще, т.к. из родителя стиль

2023-08-08 13:58 UTC, KseniaT3 commented on styles/styles.css
> +.product-card .product-card-title {
не могу никак убрать подчеркивание ссылки. пробовала может так получится.

2023-08-09 21:54 UTC, merged